baseURL = "https://mitmproxy.org/"
languageCode = "en-us"
title = "mitmproxy.org"
theme = "mitmproxy"
publishDir = "../public"
relativeURLs = true
googleAnalytics = "UA-4150636"

[params]
  version = "3.0.3"

[indexes]
  tag = "tags"
