baseURL = "https://mitmproxy.org/"
languageCode = "en-us"
title = "mitmproxy.org"
theme = "mitmproxy"
publishDir = "../public"
relativeURLs = true
googleAnalytics = "UA-4150636-13"

[params]
  version = "4.0.0"

[indexes]
  tag = "tags"
